# Binance API Configuration
binance:
  # API credentials (use environment variables)
  api_key: ${BINANCE_API_KEY}
  api_secret: ${BINANCE_API_SECRET}
  
  # Connection settings
  testnet: true  # Set to false for live trading
  timeout: 30
  retry_attempts: 3
  
  # Rate limiting
  requests_per_minute: 1200
  orders_per_second: 10
  
  # Data streams
  websocket_timeout: 30
  ping_interval: 20
  
# Trading pairs
pairs:
  primary:
    - "BTCUSDT"
    - "ETHUSDT"
    - "BNBUSDT"
    - "ADAUSDT"
    - "SOLUSDT"
  
  secondary:
    - "MATICUSDT"
    - "AVAXUSDT"
    - "DOTUSDT"
    - "LINKUSDT"
    - "UNIUSDT" 