# Strategy Configuration
strategies:
  # Scalping strategies
  micro_scalping:
    enabled: true
    timeframe: "1s"
    profit_target: 0.003   # 0.3%
    stop_loss: 0.001       # 0.1%
    max_hold_time: 300     # 5 minutes
    
  order_book_imbalance:
    enabled: true
    imbalance_threshold: 0.7
    depth_levels: 10
    min_order_size: 1000
    
  momentum_scalping:
    enabled: true
    timeframe: "5s"
    momentum_period: 20
    momentum_threshold: 0.002
    
  # Machine learning strategies
  ml_prediction:
    enabled: true
    model_type: "LSTM"
    prediction_horizon: 60  # seconds
    confidence_threshold: 0.75
    retrain_interval: 3600  # 1 hour
    
  # Arbitrage strategies
  cross_exchange_arbitrage:
    enabled: false  # Requires multiple exchanges
    min_profit_threshold: 0.005
    
  statistical_arbitrage:
    enabled: true
    pairs: ["BTCUSDT", "ETHUSDT"]
    lookback_period: 1440  # 24 hours
    zscore_threshold: 2.0 